name: Run GMeet Recorder

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 18:00 CST / 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  record:
    runs-on: ubuntu-latest
    env:
      BACKEND: gmail
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      MEET_URL: ${{ secrets.MEET_URL }}
      VIDEO_NAME: video
      OUTPUT_DIR: /output
      MAX_DURATION: 14400
      MIN_DURATION: 1800
      ASK_JOIN: True
      FRAC_TO_EXIT: 0.90
      RESOLUTION: 1920x1080
      FAST: False
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - uses: browser-actions/setup-firefox@v1
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install curl pulseaudio ffmpeg xvfb
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run recorder
        run: |
          sudo mkdir -p /output
          sudo chmod 777 /output
          xvfb-run --auto-servernum bash ./sources/driver.sh
      
      - name: Upload recording
        uses: actions/upload-artifact@v4
        with:
          name: recording
          path: /output/

