name: Run GMeet Recorder

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 18:00 CST / 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  record:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      MEET_URL: ${{ secrets.MEET_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install curl pulseaudio ffmpeg xvfb firefox-esr
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install geckodriver
        run: bash ./sources/get_geckodriver.sh
      - name: Run recorder
        run: |
          sudo mkdir -p /output
          sudo chmod 777 /output
          bash ./sources/driver.sh
      - name: Upload recording
        uses: actions/upload-artifact@v3
        with:
          name: recording
          path: /output/

